-- CREATE DATABASE EN52493_07_03_2023 
-- DATABASE CREATED AND COMMENTED OUT


USE EN52493_07_03_2023

-- Data added into EN52493_07_03_2023 and code commented out 

/*
CREATE TABLE [dbo].[EMPLOYEE](
	[BirthDate] [date] NOT NULL,
	[Gender] [nchar](1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[JobTitle] [nvarchar](50) NOT NULL
) ON [PRIMARY]

GO
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE9F70A00 AS Date), N'M', N'Ken', N'Sánchez', N'Chief Executive Officer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x7BFB0A00 AS Date), N'F', N'Terri', N'Duffy', N'Vice President of Engineering')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x2A000B00 AS Date), N'M', N'Roberto', N'Tamburello', N'Engineering Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x53000B00 AS Date), N'M', N'Rob', N'Walters', N'Senior Tool Designer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x99E00A00 AS Date), N'F', N'Gail', N'Erickson', N'Design Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCDE90A00 AS Date), N'M', N'Jossef', N'Goldberg', N'Design Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB1110B00 AS Date), N'M', N'Dylan', N'Miller', N'Research and Development Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA9100B00 AS Date), N'F', N'Diane', N'Margheim', N'Research and Development Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x25060B00 AS Date), N'F', N'Gigi', N'Matthew', N'Research and Development Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x810E0B00 AS Date), N'M', N'Michael', N'Raheem', N'Research and Development Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB4040B00 AS Date), N'M', N'Ovidiu', N'Cracium', N'Senior Tool Designer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x59EA0A00 AS Date), N'M', N'Thierry', N'D''Hers', N'Tool Designer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE9140B00 AS Date), N'F', N'Janice', N'Galvin', N'Tool Designer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB7060B00 AS Date), N'M', N'Michael', N'Sullivan', N'Senior Design Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDCEC0A00 AS Date), N'F', N'Sharon', N'Salavaria', N'Design Engineer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA9000B00 AS Date), N'M', N'David', N'Bradley', N'Marketing Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF5110B00 AS Date), N'M', N'Kevin', N'Brown', N'Marketing Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE4040B00 AS Date), N'M', N'John', N'Wood', N'Marketing Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC0040B00 AS Date), N'F', N'Mary', N'Dempsey', N'Marketing Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA7000B00 AS Date), N'F', N'Wanida', N'Benshoof', N'Marketing Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x30100B00 AS Date), N'M', N'Terry', N'Eminhizer', N'Marketing Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x07120B00 AS Date), N'M', N'Sariya', N'Harnpadoungsataya', N'Marketing Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCFEE0A00 AS Date), N'F', N'Mary', N'Gibson', N'Marketing Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB9060B00 AS Date), N'F', N'Jill', N'Williams', N'Marketing Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCC0B0B00 AS Date), N'M', N'James', N'Hamilton', N'Vice President of Production')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8B0B0B00 AS Date), N'M', N'Peter', N'Krebs', N'Production Control Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x59E60A00 AS Date), N'F', N'Jo', N'Brown', N'Production Supervisor - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x30130B00 AS Date), N'M', N'Guy', N'Gilbert', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1C070B00 AS Date), N'M', N'Mark', N'McArthur', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x64150B00 AS Date), N'F', N'Britta', N'Simon', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x99100B00 AS Date), N'F', N'Margie', N'Shoop', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF5030B00 AS Date), N'F', N'Rebecca', N'Laszlo', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x31030B00 AS Date), N'M', N'Annik', N'Stahl', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1B120B00 AS Date), N'F', N'Suchitra', N'Mohan', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x40030B00 AS Date), N'M', N'Brandon', N'Heidepriem', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x070E0B00 AS Date), N'M', N'Jose', N'Lugo', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE8100B00 AS Date), N'M', N'Chris', N'Okelberry', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE0F40A00 AS Date), N'F', N'Kim', N'Abercrombie', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA4FB0A00 AS Date), N'M', N'Ed', N'Dudenhoefer', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4FE50A00 AS Date), N'F', N'JoLynn', N'Dobney', N'Production Supervisor - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x70FE0A00 AS Date), N'M', N'Bryan', N'Baker', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x010E0B00 AS Date), N'M', N'James', N'Kramer', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x2B140B00 AS Date), N'F', N'Nancy', N'Anderson', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4B160B00 AS Date), N'M', N'Simon', N'Rapier', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x17100B00 AS Date), N'M', N'Thomas', N'Michaels', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF1010B00 AS Date), N'M', N'Eugene', N'Kogan', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE1130B00 AS Date), N'M', N'Andrew', N'Hill', N'Production Supervisor - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDBE50A00 AS Date), N'F', N'Ruth', N'Ellerbrock', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x95E50A00 AS Date), N'M', N'Barry', N'Johnson', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x32E60A00 AS Date), N'M', N'Sidney', N'Higa', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x00E60A00 AS Date), N'M', N'Jeffrey', N'Ford', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9EE50A00 AS Date), N'F', N'Doris', N'Hartwig', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x98E50A00 AS Date), N'F', N'Diane', N'Glimp', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A110B00 AS Date), N'F', N'Bonnie', N'Kearney', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9BE50A00 AS Date), N'M', N'Taylor', N'Maxwell', N'Production Supervisor - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA3130B00 AS Date), N'F', N'Denise', N'Smith', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x73FB0A00 AS Date), N'M', N'Frank', N'Miller', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA3100B00 AS Date), N'M', N'Kendall', N'Keil', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF4060B00 AS Date), N'M', N'Bob', N'Hohman', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x58030B00 AS Date), N'M', N'Pete', N'Male', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x32150B00 AS Date), N'F', N'Diane', N'Tibbott', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1BE60A00 AS Date), N'M', N'John', N'Campbell', N'Production Supervisor - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF0E30A00 AS Date), N'M', N'Maciej', N'Dusza', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x79FE0A00 AS Date), N'M', N'Michael', N'Zwilling', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAFF90A00 AS Date), N'M', N'Randy', N'Reeves', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x7BF90A00 AS Date), N'M', N'Karan', N'Khanna', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF2010B00 AS Date), N'M', N'Jay', N'Adams', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9BFB0A00 AS Date), N'M', N'Charles', N'Fitzgerald', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8F170B00 AS Date), N'M', N'Steve', N'Masters', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9E0E0B00 AS Date), N'M', N'David', N'Ortiz', N'Production Technician - WC60')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x72140B00 AS Date), N'M', N'Michael', N'Ray', N'Production Supervisor - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBC030B00 AS Date), N'M', N'Steven', N'Selikoff', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE90C0B00 AS Date), N'F', N'Carole', N'Poland', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8B150B00 AS Date), N'M', N'Bjorn', N'Rettig', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A0B0B00 AS Date), N'M', N'Michiko', N'Osada', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A140B00 AS Date), N'F', N'Carol', N'Philips', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4A0C0B00 AS Date), N'F', N'Merav', N'Netz', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x69120B00 AS Date), N'M', N'Reuben', N'D''sa', N'Production Supervisor - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDAF40A00 AS Date), N'M', N'Eric', N'Brown', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8AFA0A00 AS Date), N'M', N'Sandeep', N'Kaliyath', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xEAFA0A00 AS Date), N'M', N'Mihail', N'Frintu', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x72FE0A00 AS Date), N'M', N'Jack', N'Creasey', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE6FE0A00 AS Date), N'M', N'Patrick', N'Cook', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC8DF0A00 AS Date), N'M', N'Frank', N'Martinez', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9EFA0A00 AS Date), N'M', N'Brian', N'Goldstein', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB8FC0A00 AS Date), N'M', N'Ryan', N'Cornelsen', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x980D0B00 AS Date), N'M', N'Cristian', N'Petculescu', N'Production Supervisor - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE3F40A00 AS Date), N'F', N'Betsy', N'Stadick', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A110B00 AS Date), N'M', N'Patrick', N'Wedge', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x07110B00 AS Date), N'F', N'Danielle', N'Tiedt', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0D110B00 AS Date), N'F', N'Kimberly', N'Zimmerman', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1F110B00 AS Date), N'M', N'Tom', N'Vande Velde', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF4070B00 AS Date), N'M', N'Kok-Ho', N'Loh', N'Production Supervisor - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5DFD0A00 AS Date), N'M', N'Russell', N'Hunter', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x08110B00 AS Date), N'M', N'Jim', N'Scardelis', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDB150B00 AS Date), N'F', N'Elizabeth', N'Keyser', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5D100B00 AS Date), N'M', N'Mandar', N'Samant', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x54050B00 AS Date), N'M', N'Sameer', N'Tejani', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x68060B00 AS Date), N'M', N'Nuan', N'Yu', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x99FD0A00 AS Date), N'M', N'Lolan', N'Song', N'Production Technician - WC50')
GO
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x98FB0A00 AS Date), N'M', N'Houman', N'Pournasseh', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF00C0B00 AS Date), N'M', N'Zheng', N'Mu', N'Production Supervisor - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x16110B00 AS Date), N'M', N'Ebru', N'Ersan', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x13110B00 AS Date), N'F', N'Mary', N'Baker', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x13110B00 AS Date), N'M', N'Kevin', N'Homer', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1C110B00 AS Date), N'M', N'John', N'Kane', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1F110B00 AS Date), N'M', N'Christopher', N'Hill', N'Production Technician - WC10')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x79140B00 AS Date), N'M', N'Jinghao', N'Liu', N'Production Supervisor - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBD040B00 AS Date), N'F', N'Alice', N'Ciccu', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCB060B00 AS Date), N'M', N'Jun', N'Cao', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDB040B00 AS Date), N'M', N'Suroor', N'Fatima', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3A050B00 AS Date), N'M', N'John', N'Evans', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x40120B00 AS Date), N'F', N'Linda', N'Moschell', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x22050B00 AS Date), N'M', N'Mindaugas', N'Krapauskas', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC6170B00 AS Date), N'F', N'Angela', N'Barbariol', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x69FF0A00 AS Date), N'M', N'Michael', N'Patten', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9A160B00 AS Date), N'M', N'Chad', N'Niswonger', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4AFB0A00 AS Date), N'M', N'Don', N'Hall', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xFB140B00 AS Date), N'M', N'Michael', N'Entin', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x17120B00 AS Date), N'F', N'Kitti', N'Lertpiriyasuwat', N'Production Technician - WC50')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x10FD0A00 AS Date), N'M', N'Pilar', N'Ackerman', N'Shipping and Receiving Supervisor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD3040B00 AS Date), N'F', N'Susan', N'Eaton', N'Stocker')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x83030B00 AS Date), N'M', N'Vamsi', N'Kuppa', N'Shipping and Receiving Clerk')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAB0D0B00 AS Date), N'F', N'Kim', N'Ralls', N'Stocker')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBCFE0A00 AS Date), N'M', N'Matthias', N'Berndt', N'Shipping and Receiving Clerk')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1C0F0B00 AS Date), N'M', N'Jimmy', N'Bischoff', N'Stocker')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x7C0C0B00 AS Date), N'M', N'David', N'Hamilton', N'Production Supervisor - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBB080B00 AS Date), N'M', N'Paul', N'Komosinski', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x70130B00 AS Date), N'M', N'Gary', N'Yukish', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x59FE0A00 AS Date), N'M', N'Rob', N'Caron', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDA160B00 AS Date), N'M', N'Baris', N'Cetinok', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x70100B00 AS Date), N'F', N'Nicole', N'Holliday', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x33170B00 AS Date), N'M', N'Michael', N'Rothkugel', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB30E0B00 AS Date), N'M', N'Eric', N'Gubbels', N'Production Supervisor - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5B0A0B00 AS Date), N'M', N'Ivo', N'Salmre', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x75FA0A00 AS Date), N'M', N'Sylvester', N'Valdez', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE6FF0A00 AS Date), N'F', N'Anibal', N'Sousa', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC0120B00 AS Date), N'F', N'Samantha', N'Smith', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCEFB0A00 AS Date), N'M', N'Hung-Fu', N'Ting', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x70E10A00 AS Date), N'M', N'Prasanna', N'Samarawickrama', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xEBFF0A00 AS Date), N'M', N'Min', N'Su', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x97F90A00 AS Date), N'F', N'Olinda', N'Turner', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x9EFB0A00 AS Date), N'M', N'Krishna', N'Sunkammurali', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF6160B00 AS Date), N'M', N'Paul', N'Singh', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD1090B00 AS Date), N'F', N'Cynthia', N'Randall', N'Production Supervisor - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x05150B00 AS Date), N'M', N'Jian Shuo', N'Wang', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x90010B00 AS Date), N'F', N'Sandra', N'Reátegui Alayo', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3D140B00 AS Date), N'M', N'Jason', N'Watters', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xEA0C0B00 AS Date), N'M', N'Andy', N'Ruth', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5D0B0B00 AS Date), N'M', N'Michael', N'Vanderhyde', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x36040B00 AS Date), N'M', N'Rostislav', N'Shabalin', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x96030B00 AS Date), N'M', N'Yuhong', N'Li', N'Production Supervisor - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0F000B00 AS Date), N'M', N'Hanying', N'Feng', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x2EF50A00 AS Date), N'M', N'Raymond', N'Sam', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x83140B00 AS Date), N'M', N'Fadi', N'Fakhouri', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF8FF0A00 AS Date), N'M', N'Lane', N'Sacksteder', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4C040B00 AS Date), N'F', N'Linda', N'Randall', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x63110B00 AS Date), N'F', N'Shelley', N'Dyck', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x890E0B00 AS Date), N'M', N'Terrence', N'Earls', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x45030B00 AS Date), N'M', N'Jeff', N'Hay', N'Production Supervisor - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC50E0B00 AS Date), N'M', N'Kirk', N'Koenigsbauer', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE5080B00 AS Date), N'F', N'Laura', N'Steele', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x29160B00 AS Date), N'M', N'Alex', N'Nayberg', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF3130B00 AS Date), N'M', N'Andrew', N'Cencini', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x46140B00 AS Date), N'M', N'Chris', N'Preston', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x720C0B00 AS Date), N'M', N'Jack', N'Richins', N'Production Supervisor - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x42070B00 AS Date), N'M', N'David', N'Johnson', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x200E0B00 AS Date), N'M', N'Garrett', N'Young', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x210C0B00 AS Date), N'F', N'Susan', N'Metters', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA0030B00 AS Date), N'M', N'George', N'Li', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC2090B00 AS Date), N'M', N'David', N'Yalovsky', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x36110B00 AS Date), N'M', N'Marc', N'Ingle', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3E120B00 AS Date), N'M', N'Eugene', N'Zabokritski', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x12100B00 AS Date), N'M', N'Benjamin', N'Martin', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5D140B00 AS Date), N'M', N'Reed', N'Koch', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAA0F0B00 AS Date), N'M', N'David', N'Lawrence', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x820A0B00 AS Date), N'M', N'Russell', N'King', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAB0A0B00 AS Date), N'M', N'John', N'Frum', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x2D000B00 AS Date), N'M', N'Jan', N'Miksovsky', N'Production Technician - WC30')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x750E0B00 AS Date), N'F', N'Katie', N'McAskill-White', N'Production Supervisor - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x740E0B00 AS Date), N'M', N'Michael', N'Hines', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5C110B00 AS Date), N'M', N'Nitin', N'Mirchandani', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC7060B00 AS Date), N'F', N'Barbara', N'Decker', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x6C100B00 AS Date), N'M', N'John', N'Chen', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBE010B00 AS Date), N'M', N'Stefen', N'Hesse', N'Production Technician - WC20')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x52160B00 AS Date), N'M', N'Shane', N'Kim', N'Production Supervisor - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBE140B00 AS Date), N'F', N'Yvonne', N'McKay', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE80F0B00 AS Date), N'M', N'Douglas', N'Hite', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE1FC0A00 AS Date), N'F', N'Janeth', N'Esteves', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDB0E0B00 AS Date), N'M', N'Robert', N'Rounthwaite', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x31130B00 AS Date), N'M', N'Lionel', N'Penuchot', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x000C0B00 AS Date), N'F', N'Brenda', N'Diaz', N'Production Supervisor - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3B140B00 AS Date), N'M', N'Alejandro', N'McGuel', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x05150B00 AS Date), N'M', N'Fred', N'Northup', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x07100B00 AS Date), N'M', N'Kevin', N'Liu', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x93080B00 AS Date), N'M', N'Shammi', N'Mohamed', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4B040B00 AS Date), N'M', N'Rajesh', N'Patel', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x32140B00 AS Date), N'F', N'Lorraine', N'Nay', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA3110B00 AS Date), N'F', N'Paula', N'Nartker', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x73120B00 AS Date), N'M', N'Frank', N'Lee', N'Production Technician - WC40')
GO
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5F030B00 AS Date), N'M', N'Brian', N'Lloyd', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8F150B00 AS Date), N'M', N'Tawana', N'Nusbaum', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x7F090B00 AS Date), N'M', N'Ken', N'Myer', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x6A130B00 AS Date), N'M', N'Gabe', N'Mares', N'Production Technician - WC40')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x45080B00 AS Date), N'F', N'Lori', N'Kane', N'Production Supervisor - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCFEE0A00 AS Date), N'M', N'Stuart', N'Munson', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x5CFA0A00 AS Date), N'M', N'Greg', N'Alderson', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA3110B00 AS Date), N'M', N'Scott', N'Gode', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF3160B00 AS Date), N'F', N'Kathie', N'Flood', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD0F80A00 AS Date), N'F', N'Belinda', N'Newman', N'Production Technician - WC45')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x61040B00 AS Date), N'M', N'Hazem', N'Abolrous', N'Quality Assurance Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x16020B00 AS Date), N'M', N'Peng', N'Wu', N'Quality Assurance Supervisor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD7F40A00 AS Date), N'M', N'Sootha', N'Charncherngkha', N'Quality Assurance Technician')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAC140B00 AS Date), N'M', N'Andreas', N'Berglund', N'Quality Assurance Technician')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x85100B00 AS Date), N'M', N'Mark', N'Harrington', N'Quality Assurance Technician')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A020B00 AS Date), N'M', N'Sean', N'Alexander', N'Quality Assurance Technician')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE6010B00 AS Date), N'M', N'Zainal', N'Arifin', N'Document Control Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x38160B00 AS Date), N'M', N'Tengiz', N'Kharatishvili', N'Control Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC1110B00 AS Date), N'M', N'Sean', N'Chai', N'Document Control Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC2010B00 AS Date), N'F', N'Karen', N'Berge', N'Document Control Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0C120B00 AS Date), N'M', N'Chris', N'Norred', N'Control Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x63F70A00 AS Date), N'M', N'A. Scott', N'Wright', N'Master Scheduler')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDE120B00 AS Date), N'M', N'Sairaj', N'Uddin', N'Scheduling Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x210A0B00 AS Date), N'M', N'William', N'Vong', N'Scheduling Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8B0D0B00 AS Date), N'M', N'Alan', N'Brewer', N'Scheduling Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x120E0B00 AS Date), N'M', N'Brian', N'LaMee', N'Scheduling Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD7FA0A00 AS Date), N'M', N'Gary', N'Altman', N'Facilities Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xDA010B00 AS Date), N'M', N'Christian', N'Kleinerman', N'Maintenance Supervisor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0DFA0A00 AS Date), N'F', N'Lori', N'Penor', N'Janitor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x05FC0A00 AS Date), N'M', N'Stuart', N'Macrae', N'Janitor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD7E20A00 AS Date), N'F', N'Jo', N'Berry', N'Janitor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8AFA0A00 AS Date), N'M', N'Pat', N'Coleman', N'Janitor')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x95FB0A00 AS Date), N'M', N'Magnus', N'Hedlund', N'Facilities Administrative Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCE010B00 AS Date), N'F', N'Laura', N'Norman', N'Chief Financial Officer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xF2010B00 AS Date), N'F', N'Paula', N'Barreto de Mattos', N'Human Resources Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x33020B00 AS Date), N'M', N'Grant', N'Culbertson', N'Human Resources Administrative Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA1030B00 AS Date), N'M', N'Hao', N'Chen', N'Human Resources Administrative Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x080E0B00 AS Date), N'M', N'Vidur', N'Luthra', N'Recruiter')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x770E0B00 AS Date), N'F', N'Mindy', N'Martin', N'Benefits Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x6A050B00 AS Date), N'M', N'Willis', N'Johnson', N'Recruiter')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x820C0B00 AS Date), N'M', N'David', N'Liu', N'Accounts Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0A020B00 AS Date), N'F', N'Deborah', N'Poe', N'Accounts Receivable Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xFE010B00 AS Date), N'F', N'Candy', N'Spoon', N'Accounts Receivable Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3A0E0B00 AS Date), N'M', N'Bryan', N'Walton', N'Accounts Receivable Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCC010B00 AS Date), N'F', N'Barbara', N'Moreland', N'Accountant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x63030B00 AS Date), N'M', N'Dragan', N'Tomic', N'Accounts Payable Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x54060B00 AS Date), N'F', N'Janet', N'Sheperdigian', N'Accounts Payable Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC6060B00 AS Date), N'M', N'Mike', N'Seamans', N'Accountant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x4F0E0B00 AS Date), N'F', N'Wendy', N'Kahn', N'Finance Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCC040B00 AS Date), N'F', N'Sheela', N'Word', N'Purchasing Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x180E0B00 AS Date), N'M', N'Mikael', N'Sandberg', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD7FF0A00 AS Date), N'M', N'Arvind', N'Rao', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x87FA0A00 AS Date), N'F', N'Linda', N'Meisner', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x81FA0A00 AS Date), N'M', N'Fukiko', N'Ogisu', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD1F40A00 AS Date), N'M', N'Gordon', N'Hee', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0FE00A00 AS Date), N'M', N'Frank', N'Pellow', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x18FD0A00 AS Date), N'M', N'Eric', N'Kurjan', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xAAFA0A00 AS Date), N'F', N'Erin', N'Hagens', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x1BFE0A00 AS Date), N'M', N'Ben', N'Miller', N'Buyer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC0040B00 AS Date), N'F', N'Annette', N'Hill', N'Purchasing Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB4040B00 AS Date), N'M', N'Reinout', N'Hillmann', N'Purchasing Assistant')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x56F10A00 AS Date), N'M', N'David', N'Barber', N'Assistant to the Chief Financial Officer')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB6010B00 AS Date), N'F', N'Jean', N'Trenary', N'Information Services Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x870D0B00 AS Date), N'F', N'Stephanie', N'Conroy', N'Network Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x8C030B00 AS Date), N'M', N'Ashvini', N'Sharma', N'Network Administrator')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x12080B00 AS Date), N'M', N'Peter', N'Connelly', N'Network Administrator')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x2E050B00 AS Date), N'F', N'Karen', N'Berg', N'Application Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x30130B00 AS Date), N'M', N'Ramesh', N'Meyyappan', N'Application Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x0C120B00 AS Date), N'M', N'Dan', N'Bacon', N'Application Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xE4000B00 AS Date), N'M', N'François', N'Ajenstat', N'Database Administrator')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xCE010B00 AS Date), N'M', N'Dan', N'Wilson', N'Database Administrator')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xBE0E0B00 AS Date), N'F', N'Janaina', N'Bueno', N'Application Specialist')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xD3030B00 AS Date), N'M', N'Brian', N'Welcker', N'Vice President of Sales')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x3FDF0A00 AS Date), N'M', N'Stephen', N'Jiang', N'North American Sales Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC6F70A00 AS Date), N'M', N'Michael', N'Blythe', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB7070B00 AS Date), N'F', N'Linda', N'Mitchell', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xC0EE0A00 AS Date), N'F', N'Jillian', N'Carson', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x7E000B00 AS Date), N'M', N'Garrett', N'Vargas', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x00FF0A00 AS Date), N'M', N'Tsvi', N'Reiter', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x42000B00 AS Date), N'F', N'Pamela', N'Ansman-Wolfe', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA3F60A00 AS Date), N'M', N'Shu', N'Ito', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x95F00A00 AS Date), N'M', N'José', N'Saraiva', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x18FF0A00 AS Date), N'M', N'David', N'Campbell', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xA8040B00 AS Date), N'M', N'Tete', N'Mensa-Annan', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x66000B00 AS Date), N'M', N'Syed', N'Abbas', N'Pacific Sales Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x63030B00 AS Date), N'F', N'Lynn', N'Tsoflias', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xB4E70A00 AS Date), N'F', N'Amy', N'Alberts', N'European Sales Manager')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x19010B00 AS Date), N'F', N'Rachel', N'Valdez', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0xABF60A00 AS Date), N'F', N'Jae', N'Pak', N'Sales Representative')
INSERT [dbo].[EMPLOYEE] ([BirthDate], [Gender], [FirstName], [LastName], [JobTitle]) VALUES (CAST(0x6C010B00 AS Date), N'M', N'Ranjit', N'Varkey Chudukatil', N'Sales Representative')
*/

-- Creating a new table with the desired column order and primary key
CREATE TABLE dbo.EMPLOYEE_NEW (
    ID_EMPLOYEE INT IDENTITY(1,1) PRIMARY KEY,
    BirthDate DATE,
    Gender CHAR(1),
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    JobTitle VARCHAR(50)
);

-- Inserting data from the original table into the new table
INSERT INTO dbo.EMPLOYEE_NEW (BirthDate, Gender, FirstName, LastName, JobTitle)
SELECT BirthDate, Gender, FirstName, LastName, JobTitle
FROM dbo.EMPLOYEE;

-- Dropping the original table
DROP TABLE dbo.EMPLOYEE;

-- Renaming the new table to the original table name
EXEC sp_rename 'dbo.EMPLOYEE_NEW', 'EMPLOYEE';

-- Retrieving and displaying records from the modified "EMPLOYEE" table
SELECT * FROM dbo.EMPLOYEE;

